name: reconnect_yaml
main: net.md_5.bungee.module.reconnect.yaml.PluginYaml
version: git:reconnect_yaml:1.21-R0.1-SNAPSHOT:6fe6469:unknown
description: Provides reconnect location functionality in locations.yml
author: SpigotMC
