name: cmd_alert
main: net.md_5.bungee.module.cmd.alert.PluginAlert
version: git:cmd_alert:1.21-R0.1-SNAPSHOT:fd3c60c:unknown
description: Provides the alert and alertraw commands
author: SpigotMC
